# Generated by Django 4.2.6 on 2023-11-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('item_name', models.TextField(default='')),
                ('item_count', models.TextField(default='')),
                ('supplier_id', models.IntegerField(default=0)),
                ('ordered_date', models.DateField()),
                ('expiry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SupplierList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(default='')),
                ('address', models.TextField(default='')),
                ('contact_no', models.TextField(default='')),
            ],
        ),
    ]
